// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mcp.server.enabled": boolean;
      "mcp.server.port": number;
      "markitdown.enabled": boolean;
      "markitdown.path": string;
    };
  }
}
